<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insertar Compra</title>
</head>
<body>
<div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="editar/<?= $cliente->id ?>" method="POST">
                    <div class="form-group">
                        <label for="mensaje">Nombre</label>
                        <input class="form-control" name="nombre" rows="3" placeholder="Escribe tu mensaje" value = "<?= $cliente->Nombre ?>"> </input>
                    </div>
                    <div class="form-group">
                        <label for="mensaje">Dirección</label>
                        <input class="form-control"  name="direccion" rows="3" placeholder="Escribe el total" value = "<?= $cliente->Dirección ?>"></input>
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>