<?php var_dump($cliente)?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insertar Compra</title>
</head>
<body>
<div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="aniadir/<?= $cliente->id ?>" method="POST">
                    <div class="form-group">
                        <label for="total">Total</label>
                        <input type="number" class="form-control" name="total" placeholder="Ingresa el monto">
                    </div>
                    <div class="form-group">
                        <label for="email">Dirección</label>
                        <input type="text" class="form-control" name="direccion" placeholder="Ingresa tu direccion" value = "<?= $cliente->Dirección ?>">
                    </div>
                    <div class="form-group">
                        <label for="mensaje">Mensaje</label>
                        <textarea class="form-control" name="mensaje" rows="3" placeholder="Escribe tu mensaje"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>